'use client';

import { useEffect, useState } from 'react';
import { createHighlighter, type Highlighter } from 'shiki';

interface CodeBlockProps {
  code: string;
  language?: string;
  showLineNumbers?: boolean;
}

export function CodeBlock({
  code,
  language = 'typescript',
  showLineNumbers = false,
}: CodeBlockProps) {
  const [highlightedCode, setHighlightedCode] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let highlighter: Highlighter | null = null;

    async function highlight() {
      try {
        highlighter = await createHighlighter({
          themes: ['min-light', 'github-dark-dimmed'],
          langs: ['typescript', 'tsx', 'javascript', 'jsx', 'json', 'css', 'html'],
        });

        const html = highlighter.codeToHtml(code, {
          lang: language,
          themes: {
            light: 'min-light',
            dark: 'github-dark-dimmed',
          },
        });

        // Add custom classes to the <pre> tag generated by Shiki for rounded corners and padding
        const styledHtml = html.replace(
          '<pre class="shiki',
          '<pre class="shiki rounded-lg p-lg overflow-x-auto'
        );

        setHighlightedCode(styledHtml);
        setIsLoading(false);
      } catch (error) {
        console.error('Failed to highlight code:', error);
        setIsLoading(false);
      }
    }

    highlight();

    return () => {
      if (highlighter) {
        highlighter.dispose();
      }
    };
  }, [code, language]);

  if (isLoading) {
    return (
      <pre className="bg-muted/50 rounded-lg p-lg overflow-x-auto text-sm animate-pulse">
        <code className="font-mono">{code}</code>
      </pre>
    );
  }

  return (
    <div
      className="shiki-wrapper"
      dangerouslySetInnerHTML={{ __html: highlightedCode }}
    />
  );
}
